[aws_servers]
amazon_linux ansible_host=13.61.145.29 ansible_user=ec2-user
ubuntu ansible_host=56.228.15.146 ansible_user=ubuntu

[aws_servers:vars]
ansible_ssh_private_key_file=/home/user1/ansible/keys/Key1.pem
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
